### ISSUE TITLE
Cannot find module '@octokit/core'

### ISSUE THREAD

**Issue by ilyaulyanov** [octokit/plugin-paginate-rest.js#30]
Hi,

I'm using Yarn 2 with TypeScript, and, when using `@octokit/rest`, I'm getting a `tsc` error:

<img width="1425" alt="Screen Shot 2020-04-13 at 9 01 23 PM" src="https://user-images.githubusercontent.com/5951523/79184940-6899d800-7dca-11ea-852a-7ad903865c38.png">

It looks like `@octokit/core` should be a `dependency` instead of `devDependency`. I fixed it on my end by using [packageExtensions](https://yarnpkg.com/configuration/yarnrc#packageExtensions)(via https://github.com/yarnpkg/berry/issues/893), but it's a workaround:
```yml
packageExtensions:
  "@octokit/plugin-paginate-rest@*":
    dependencies:
      "@octokit/core": "^v2.0.0"
```

I'm not using `plugin-paginate-rest` directly, but rather as a dependency of ` "@octokit/rest": "^17.2.1"`
